.TH "md__r_e_a_d_m_e" 3 "Sexta, 5 de Outubro de 2018" "Version 1.0.0" "Tratamento de polígonos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- dca1202_Alisson Sousa Moreira 

.SS "Projeto da 2ª unidade de Programação Avançada"
.PP
.SS "Tratamento de polígonos: Criação das classes \fBPoint\fP, Polígono e Retângulo"

