.TH "Point" 3 "Sexta, 5 de Outubro de 2018" "Version 1.0.0" "Tratamento de polígonos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point
.SH SYNOPSIS
.br
.PP
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBPoint\fP ()"
.br
.RI "\fBPoint\fP\&. "
.ti -1c
.RI "\fB~Point\fP ()"
.br
.RI "~Point "
.ti -1c
.RI "void \fBsetX\fP (float mx)"
.br
.RI "setX "
.ti -1c
.RI "void \fBsetY\fP (float my)"
.br
.RI "setY "
.ti -1c
.RI "void \fBsetXY\fP (float mx, float my)"
.br
.RI "setXY "
.ti -1c
.RI "float \fBgetX\fP (void)"
.br
.RI "getX "
.ti -1c
.RI "float \fBgetY\fP (void)"
.br
.RI "getY "
.ti -1c
.RI "void \fBadd\fP (\fBPoint\fP p)"
.br
.RI "add "
.ti -1c
.RI "void \fBsub\fP (\fBPoint\fP p)"
.br
.RI "sub "
.ti -1c
.RI "void \fBsub\fP (float a, float b)"
.br
.RI "sub "
.ti -1c
.RI "float \fBnorma\fP (void)"
.br
.RI "norma "
.ti -1c
.RI "void \fBtranslada\fP (float a, float b)"
.br
.RI "translada "
.ti -1c
.RI "void \fBimprime\fP (void)"
.br
.RI "imprime "
.in -1c
.SH "Funções membros"
.PP 
.SS "void Point::add (\fBPoint\fP p)"

.PP
add 
.PP
\fBParâmetros:\fP
.RS 4
\fIp\fP 
.RE
.PP

.SS "float Point::getX (void)"

.PP
getX 
.PP
\fBRetorna:\fP
.RS 4

.RE
.PP

.SS "float Point::getY (void)"

.PP
getY 
.PP
\fBRetorna:\fP
.RS 4

.RE
.PP

.SS "float Point::norma (void)"

.PP
norma 
.PP
\fBRetorna:\fP
.RS 4

.RE
.PP

.SS "void Point::setX (float mx)"

.PP
setX 
.PP
\fBParâmetros:\fP
.RS 4
\fImx\fP 
.RE
.PP

.SS "void Point::setXY (float mx, float my)"

.PP
setXY 
.PP
\fBParâmetros:\fP
.RS 4
\fImx\fP 
.br
\fImy\fP 
.RE
.PP

.SS "void Point::setY (float my)"

.PP
setY 
.PP
\fBParâmetros:\fP
.RS 4
\fImy\fP 
.RE
.PP

.SS "void Point::sub (\fBPoint\fP p)"

.PP
sub 
.PP
\fBParâmetros:\fP
.RS 4
\fIp\fP 
.RE
.PP

.SS "void Point::sub (float a, float b)"

.PP
sub 
.PP
\fBParâmetros:\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP

.SS "void Point::translada (float a, float b)"

.PP
translada 
.PP
\fBParâmetros:\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Tratamento de polígonos a partir do código-fonte\&.
