.TH "Poligono" 3 "Sexta, 5 de Outubro de 2018" "Version 1.0.0" "Tratamento de polígonos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poligono
.SH SYNOPSIS
.br
.PP
.PP
Superclasse de \fBRetangulo\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBPoligono\fP ()"
.br
.RI "\fBPoligono\fP\&. "
.ti -1c
.RI "\fB~Poligono\fP ()"
.br
.RI "~Poligono "
.ti -1c
.RI "void \fBsetVertices\fP (float mx, float my)"
.br
.RI "setVertices "
.ti -1c
.RI "int \fBgetVertices\fP (void)"
.br
.RI "getVertices "
.ti -1c
.RI "float \fBarea\fP (void)"
.br
.RI "area "
.ti -1c
.RI "void \fBtranslada\fP (float a, float b)"
.br
.RI "translada "
.ti -1c
.RI "void \fBrotaciona\fP (float theta, \fBPoint\fP p, float a, float b)"
.br
.RI "rotaciona "
.ti -1c
.RI "void \fBimprime\fP (void)"
.br
.RI "imprime "
.in -1c
.SH "Funções membros"
.PP 
.SS "float Poligono::area (void)"

.PP
area 
.PP
\fBRetorna:\fP
.RS 4

.RE
.PP

.SS "int Poligono::getVertices (void)"

.PP
getVertices 
.PP
\fBRetorna:\fP
.RS 4

.RE
.PP

.SS "void Poligono::rotaciona (float theta, \fBPoint\fP p, float a, float b)"

.PP
rotaciona 
.PP
\fBParâmetros:\fP
.RS 4
\fItheta\fP 
.br
\fIp\fP 
.RE
.PP

.SS "void Poligono::setVertices (float mx, float my)"

.PP
setVertices 
.PP
\fBParâmetros:\fP
.RS 4
\fImx\fP 
.br
\fImy\fP 
.RE
.PP

.SS "void Poligono::translada (float a, float b)"

.PP
translada 
.PP
\fBParâmetros:\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Tratamento de polígonos a partir do código-fonte\&.
