.TH "Retangulo" 3 "Sexta, 5 de Outubro de 2018" "Version 1.0.0" "Tratamento de polígonos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Retangulo
.SH SYNOPSIS
.br
.PP
.PP
Subclasse de \fBPoligono\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBRetangulo\fP (float x, float y, float largura, float altura)"
.br
.RI "\fBRetangulo\fP\&. "
.ti -1c
.RI "\fB~Retangulo\fP ()"
.br
.RI "~Retangulo "
.in -1c
.SH "Construtores e Destrutores"
.PP 
.SS "Retangulo::Retangulo (float x, float y, float largura, float altura)"

.PP
\fBRetangulo\fP\&. 
.PP
\fBParâmetros:\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.br
\fIlargura\fP 
.br
\fIaltura\fP 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Tratamento de polígonos a partir do código-fonte\&.
